# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Henno Havenga 
email: hennohavenga@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Geo and spatial science graduate student, Debian GNU\Linux user,
  open-source advocate, runner and dog lover.  I'm navigating this strange
  new world of programming, blogging and sharing. Bare with me.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://h-havenga.github.io/" # the base hostname & protocol for your site
enforce_ssl: "h-havenga.github.io"
twitter_username: h_havenga
github_username: h-havenga

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
disqus:
  shortname: hh92

# Google Analytics
google_analytics: UA-108907924-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
